Document: ubuntu-mate-guide
Title: Debian ubuntu-mate-guide Manual
Author: <insert document author here>
Abstract: This manual describes what ubuntu-mate-guide is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ubuntu-mate-guide/ubuntu-mate-guide.sgml.gz

Format: postscript
Files: /usr/share/doc/ubuntu-mate-guide/ubuntu-mate-guide.ps.gz

Format: text
Files: /usr/share/doc/ubuntu-mate-guide/ubuntu-mate-guide.text.gz

Format: HTML
Index: /usr/share/doc/ubuntu-mate-guide/html/index.html
Files: /usr/share/doc/ubuntu-mate-guide/html/*.html
